### ISSUE TITLE
Add option to disable the notification sound

### ISSUE THREAD

**Issue by samueljun** [samueljun/tomato-clock#26]

**Comment by murarisumit** [comment]
this is already done right, the yellow color 'reset' button in firefox ?

**Comment by murarisumit** [comment]
@samueljun are you working on it, can I take this task up ?

**Comment by samueljun** [comment]
I started on a settings page already a bit ago for #21. Let me get that landed and you're welcome to start on it :)

**Comment by samueljun** [comment]
Whoops sorry I got carried away. I ended up implementing this task since it was easier than #21. I'll publish a build out to the public soon. Feel free to grab another task if you'd like :)
