### ISSUE TITLE
Add "Reset to default" button in the preferences

### ISSUE THREAD

**Issue by samueljun** [samueljun/tomato-clock#29]
This will be helpful for users to get back to the default settings.

**Comment by murarisumit** [comment]
this is already done right, 'yellow' color reset button in firefox.

**Comment by samueljun** [comment]
Ah no this was actually a follow for when #21 finished. Since #21 would allow users to customize their times, it would be good to allow users to get back to the default settings.

**Comment by samueljun** [comment]
Solved by 8059f3dc0d71fbad8b7aed43e5147a986a4d8bbd
