### ISSUE TITLE
Any chance to add a 5217 mode to your timer?

### ISSUE THREAD

**Issue by nerotic** [samueljun/tomato-clock#33]
http://www.androidauthority.com/5217-productivity-app-691121/

Would love to have this functionality in Firefox and I don't believe it would be too much big a deal to implement.

**Comment by samueljun** [comment]
One the features enhancements on the chopping block is the ability to customize the various timers:  #21. That should allow you to create a 52 minute work session and a 17 minute break.

**Comment by nerotic** [comment]
That would be great, how high on the priority list is this for you?

**Comment by samueljun** [comment]
This is pretty highly requested so I'll be prioritizing this for the next release :)

**Comment by nerotic** [comment]
You might even want to spin it off so you could say you were the first to create a 5217 extension
