### ISSUE TITLE
Timer does not run automatically

### ISSUE THREAD

**Issue by MJae** [samueljun/tomato-clock#45]
The timer does not run on its own. I have to click on it every time a want a new phase for the timer. 

I am not sure if this is supposed to be automatically running, though. If it isn't, please add such a feature.

**Comment by samueljun** [comment]
Thanks for the idea! I'm gonna close this issue as a duplicate since it is similar to #27. I do like the idea of also allowing for an infinite number of cycles. I'll make a note of that in #27.

**Comment by MJae** [comment]
You're welcome. I'd also like to add further notes so I'll add that to the open issue.
