### ISSUE TITLE
addittion of an annual date range in the stats

### ISSUE THREAD

**Issue by Tomer-Daloomi** [samueljun/tomato-clock#48]
Hi there!! for me (and I believe that others might feel the same) - It would highly contribute to the long term effectiveness of the studying process if viewing the studying patterns over larger spans of time (annually and such) would have been possible. could you please add this option?

thanks in advance for reviewing the issue and for the elegant implementation of the add-on so far! :)

**Comment by samueljun** [comment]
Added to v4.3.0 :)
