### ISSUE TITLE
no sound in firefox in linux

### ISSUE THREAD

**Issue by waynongithub** [samueljun/tomato-clock#49]
Hi, using firefox 57 and 59 in linux mint 18.3
I have no problem with sound in websites in the browser, but the tomato-clock makes no sound. Any suggestions where i can start looking?
tnx

btw. Thanks for your project!

**Comment by samueljun** [comment]
Hi @waynongithub I added the ability to have a notification sound just for the Linux use case actually. You can enable a notification sound by going into the about:addons page, clicking on "Extensions", clicking on "Preferences" for the Tomato Click extension, checking on the "Notification sound" option, and then clicking "Save.

<img width="562" alt="screenshot of preferences page for the tomato clock extension" src="https://user-images.githubusercontent.com/1808588/42016517-ada5d71a-7a60-11e8-87aa-235fee67e9a5.png">

**Comment by LecJackS** [comment]
I'm having the same issue on firefox on Ubuntu.Disabling and reenabling that checkbox and saving in between didn't solve the problem.

Any idea?
