### ISSUE TITLE
Stats not working on Firefox

### ISSUE THREAD

**Issue by hrnec** [samueljun/tomato-clock#54]
Hi,
Installed as Firefox plugin, the stats are not reflecting the number of tomatoes taken.
On Chrome the graph is OK.

**Comment by samueljun** [comment]
Hi, thanks for the bug report. I'm closing this as I'm seeing that the Stats page is currently working on Firefox. Feel free to reopen with more details if you are still seeing this bug. Like a screenshot and which version you are seeing the issue.
