### ISSUE TITLE
Bug: History data are cleared at new tomato finished on the next day.

### ISSUE THREAD

**Issue by Mrbrom** [samueljun/tomato-clock#61]
Bug: History data are cleared at new tomato finished on the next day in chromium.

-

**Comment by samueljun** [comment]
Hi thanks for the bug report. Can you provide the following?

```
### Reproduction steps

### Expected result

### Actual result

```

**Comment by Mrbrom** [comment]
Yesterday I have clicked one pomodoro. Today it looked like
![1](https://user-images.githubusercontent.com/26968954/53185930-14a1c200-3611-11e9-991f-4277dd09cdd8.jpg) Today  I add one more and after timer stopped it was this
![2](https://user-images.githubusercontent.com/26968954/53186243-ae696f00-3611-11e9-8fe8-1cb872b5b233.jpg).
Is this a clear description of the bug? My English is not very good. :-)

**Comment by samueljun** [comment]
Thank you for the screenshots! I was able to reproduce the bug on my machine. I'll prioritize a fix for this bug.
