### ISSUE TITLE
The app doesn't sound alerts (only get the visual alert)

### ISSUE THREAD

**Issue by McAllie** [samueljun/tomato-clock#64]
**Describe the bug**
There is no sound when the 25 min are up or when the breaks are over. I usually don't notice the visual popups. I HAVE verified that the sound notification is checked and that the computer sound is on. (I do get sound from the computer system and videos.)

**To Reproduce**
1. Press Tomato button.
2. Work while app counts down to zero
3. At zero I get a popup, but no sound.

**Expected behavior** Alarm goes off at appropriate intervals

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows 7 Home Premium 32-bit SP1
 - Browser:  Firefox Quantum 
 - Version:  65.0.2 (32-bit)

**Additional context**

**Comment by samueljun** [comment]
Unfortunately I don't have a Windows 7 machine to reproduce your setup but the audio file for the "Notification sound" is [here](http://media.steampowered.com/apps/portal2/soundtrack/02/ringtones/sfx/m4a/Portal2_sfx_button_positive.m4a). Are you able to play the audio file on your machine?

**Comment by eprikazc** [comment]
I have the same issue with Firefox in Ubuntu 18.04. Prepared PR with fix (referenced by above)
