### ISSUE TITLE
time tweaking

### ISSUE THREAD

**Issue by ram-431** [samueljun/tomato-clock#69]
Time is not flexible . Need to extend timer a bit.

**Comment by samueljun** [comment]
There is the ability to customize the length of time in the extension preferences/options page. If this is not what you're referring to, would you elaborate further?

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/1808588/62431071-0df79a80-b6d9-11e9-94dd-9d37300cd866.png">

<img width="1552" alt="Screen Shot 2019-08-04 at 5 03 40 PM" src="https://user-images.githubusercontent.com/1808588/62431174-d3dac880-b6d9-11e9-8e7f-58a34fa8abc3.png">
