### ISSUE TITLE
Notification sound

### ISSUE THREAD

**Issue by YacineSahli** [samueljun/tomato-clock#80]
How can I get a notification sound when the task end ? Because I have multiple screen and I don't always see the notifications.

Is it possible to get a sound ?

**Comment by Skydler** [comment]
Hi @YacineSahli 
I believe in the preferences options of the extension there's a checkbox to enable notification sounds

**Comment by YacineSahli** [comment]
Thank you, I don't know why but by unchecking and checking it again it worked.
